baseURL = "hypha.ro"
languageCode = "en-us"
title = "Hypha"
theme = "hypha"
disablePathToLower = true

[menu]
  [[menu.main]]
    name = "traversal of feminist servers"
    url = "ATNOFS/"
    weight = 2
